## Problem 4: Regression Problem 2

### Here, you are expected to predict the lifespan of the above organism given the data from three sensors. In this case, the model is not linear. You are expected to try several (at least 3) non-linear regression models on the train split and report the following metrics on the test split (a) Mean Squared Error, (b) Mean Absolute Error.

### Models to use: Suppot Vector Regression, Linear Regression.

In [2]:
# Import Libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

In [3]:
# Load the Dataset

df1 = pd.read_csv("p2_train.csv", header=None, names=["A", "B", "C", "Target"])
df1

             A         B         C         Target
0     6.501996 -8.536983  3.422935  119980.220246
1     1.328383  8.943578 -8.145307   29890.224974
2     0.161478 -7.928351  1.628924    3245.579405
3    -8.989890  0.621330 -2.322925  411824.663771
4     5.185118  7.902611  7.559619  176097.137744
...        ...       ...       ...            ...
9995 -0.209969  0.516290  1.757739       4.730791
9996 -1.908943  8.884813 -8.949701   67718.037645
9997  5.155422  5.500823  7.804984  165778.153769
9998  7.410197 -3.096079  4.394444  212850.414030
9999  8.658392  2.129026 -2.237578  396440.751196

[10000 rows x 4 columns]

In [4]:
df2 = pd.read_csv("p2_test.csv", header=None, names=["A", "B", "C", "Target"])
df2

             A         B         C         Target
0    -1.453098 -3.535848  4.957581    5738.079257
1    -0.951478 -4.954119 -4.572673     391.728338
2     3.876805  9.707116  6.012681   72127.820634
3     4.944532  8.173724  2.526409   35939.928053
4     8.422242  1.181565  3.208955  365974.814979
...        ...       ...       ...            ...
4995  7.325928 -2.517590  0.681199  158822.870077
4996  5.063459 -1.450395 -7.034063     325.749863
4997 -6.716127  2.112438  2.746665   55743.437853
4998  8.971959 -3.130959 -5.372547  417527.327099
4999  7.204144  5.134398  6.773530  298787.904481

[5000 rows x 4 columns]

In [5]:
x = df1.drop(columns=["Target"])
y = df1["Target"]

In [6]:
# SVR

model = SVR().fit(x, y)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

mse_train = mean_squared_error(y_train, y_train_pred)
mae_train = mean_absolute_error(y_train, y_train_pred)

mse_test = mean_squared_error(y_test, y_test_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

metrics_train = {"mean_squared_error_train": mse_train,
                "mean_absolute_error_train": mae_train}

metrics_test = {"mean_squared_error_test": mse_test,
               "mean_absolute_error_test": mae_test}

print("Train_Data: ", metrics_train)
print("Test_Data: ", metrics_test)


y_pred = model.predict(df2[["A", "B", "C"]])

mse_y_pred = mean_squared_error(df2["Target"], y_pred)
mae_y_pred = mean_absolute_error(df2["Target"], y_pred)

metrics_y_pred = {"mean_squared_error_test": mse_y_pred,
                 "mean_absolute_error_test": mae_y_pred}

print("y_pred_metrics: ", metrics_y_pred)

Train_Data:  {'mean_squared_error_train': 75459864496.41516, 'mean_absolute_error_train': 147485.99229845326}
Test_Data:  {'mean_squared_error_test': 79892066388.63107, 'mean_absolute_error_test': 150288.56747878977}
y_pred_metrics:  {'mean_squared_error_test': 77888697059.87163, 'mean_absolute_error_test': 150475.59108079062}

In [7]:
# Linear Regression

Linear_model = LinearRegression().fit(x,y)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
y_train_pred = Linear_model.predict(X_train)
y_test_pred = Linear_model.predict(X_test)

mse_train = mean_squared_error(y_train, y_train_pred)
mae_train = mean_absolute_error(y_train, y_train_pred)

mse_test = mean_squared_error(y_test, y_test_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

metrics_train = {"mean_squared_error_train": mse_train,
                "mean_absolute_error_train": mae_train}

metrics_test = {"mean_squared_error_test": mse_test,
               "mean_absolute_error_test": mae_test}

print("Train_Data: ", metrics_train)
print("Test_Data: ", metrics_test)


y_pred = Linear_model.predict(df2[["A","B","C"]])

mse_y_pred = mean_squared_error(df2["Target"], y_pred)
mae_y_pred = mean_absolute_error(df2["Target"], y_pred)

metrics_y_pred_linear = {"mean_squared_error_test": mse_y_pred,
                        "mean_absolute_error_test": mae_y_pred}

print("y_pred_metrics: ", metrics_y_pred_linear)

Train_Data:  {'mean_squared_error_train': 61042815958.91605, 'mean_absolute_error_train': 173137.92936374238}
Test_Data:  {'mean_squared_error_test': 62227903330.995674, 'mean_absolute_error_test': 174542.25128146732}
y_pred_metrics:  {'mean_squared_error_test': 62332720766.18977, 'mean_absolute_error_test': 172939.29867514668}

In [8]:
#Random Forest

Random_model=RandomForestRegressor().fit(x, y)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
y_train_pred= Random_model.predict(X_train)
y_test_pred= Random_model.predict(X_test)

mse_train= mean_squared_error(y_train,y_train_pred)
mae_train= mean_absolute_error(y_train,y_train_pred)


mse_test= mean_squared_error(y_test, y_test_pred)
mae_test= mean_absolute_error(y_test, y_test_pred)


metrics_train= {"mean_squared_error_train":mse_train,
                "mean_absolute_error_train":mae_train}

metrics_test= {"mean_squared_error_test":mse_test,
                "mean_absolute_error_test":mae_test}

print("Train Data: ",metrics_train)
print("Test Data: ",metrics_test)

y_pred= Random_model.predict(df2[["A","B","C"]])

mse_y_pred= mean_squared_error(df2["Target"], y_pred)
mae_y_pred= mean_absolute_error(df2["Target"], y_pred)

metrics_y_pred_random= {"mean_squared_error_test":mse_y_pred,
                        "mean_absolute_error_test":mae_y_pred}

print("y_pred_metrics: ", metrics_y_pred_random)

Train Data:  {'mean_squared_error_train': 42037337.87369804, 'mean_absolute_error_train': 3199.5145569431083}
Test Data:  {'mean_squared_error_test': 53342943.332872845, 'mean_absolute_error_test': 3424.818861870772}
y_pred_metrics:  {'mean_squared_error_test': 322743575.1611554, 'mean_absolute_error_test': 8905.666301392575}

In [9]:
#Decision Tree

Decision_model=DecisionTreeRegressor().fit(x, y)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
y_train_pred= Decision_model.predict(X_train)
y_test_pred= Decision_model.predict(X_test)

mse_train= mean_squared_error(y_train,y_train_pred)
mae_train= mean_absolute_error(y_train,y_train_pred)


mse_test= mean_squared_error(y_test, y_test_pred)
mae_test= mean_absolute_error(y_test, y_test_pred)


metrics_train= {"mean_squared_error_train":mse_train,
                "mean_absolute_error_train":mae_train}

metrics_test= {"mean_squared_error_test":mse_test,
                "mean_absolute_error_test":mae_test}

print("Train Data: ",metrics_train)
print("Test Data: ",metrics_test)

y_pred= Decision_model.predict(df2[["A","B","C"]])

mse_y_pred= mean_squared_error(df2["Target"], y_pred)
mae_y_pred= mean_absolute_error(df2["Target"], y_pred)

metrics_y_pred_decision= {"mean_squared_error_test":mse_y_pred,
                        "mean_absolute_error_test":mae_y_pred}

print("y_pred_metrics: ", metrics_y_pred_decision)

Train Data:  {'mean_squared_error_train': 0.0, 'mean_absolute_error_train': 0.0}
Test Data:  {'mean_squared_error_test': 0.0, 'mean_absolute_error_test': 0.0}
y_pred_metrics:  {'mean_squared_error_test': 778699022.9191027, 'mean_absolute_error_test': 13865.02408678833}