##  Project 3 : Regression Problem 1


### In this problem, the task is to predict the current health (as given by the target variable) of an organism given the measurements from two biological sensors measuring their bio-markers (negative indicates that it is lesser than the average case). With this data, you are expected to try our linear regression models on the training data and report the following metrics on the test split: (a) Mean Squared Error, (b) Mean Absolute Error.

In [1]:
# Import Libraries

import pandas as pd
#import matplotlib.pyplot as plt
#import seaborn as sns
import sklearn
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score
from sklearn.linear_model import LinearRegression

In [2]:
# Load Dataset

df1 = pd.read_csv("p1_train.csv", header=None, names=["A", "B", "Target"])
df1

              A          B     Target
0     -7.262173   9.572604   5.358725
1      3.462140  10.684524 -13.275822
2    -12.996801  -3.446163  31.815190
3      7.083537 -14.074146   1.995030
4    -15.216890 -18.630651  48.812452
...         ...        ...        ...
9995  16.981033  -7.377274 -21.776089
9996   0.258434 -19.488764  22.098571
9997  17.588664  11.326009 -47.812604
9998   0.531756 -15.189405  20.791085
9999  10.763891  -2.720607 -20.735447

[10000 rows x 3 columns]

In [3]:
df2 = pd.read_csv("p1_test.csv", header=None, names=["A","B","Target"])
df2

              A          B     Target
0     15.893003  11.712829 -37.567929
1     -2.722421  -4.540615  11.475211
2    -14.587111  18.592864  11.468441
3      0.224331  16.433306 -15.159309
4    -12.215286  11.742682  17.392223
...         ...        ...        ...
4995 -14.424996   7.055352  21.402087
4996 -12.249485  12.226991  14.971488
4997 -19.242759 -18.218209  56.687193
4998 -13.561869   2.773022  26.627790
4999  -3.784030   0.979866  11.868025

[5000 rows x 3 columns]

In [4]:
x = df1.drop(columns=["Target"])
y = df1["Target"]

In [5]:
# Linear Regression

Linear_model = LinearRegression().fit(x, y)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
y_train_pred = Linear_model.predict(X_train)
y_test_pred = Linear_model.predict(X_test)

mse_train = mean_squared_error(y_train, y_train_pred)
mae_train = mean_absolute_error(y_train, y_train_pred)

mse_test = mean_squared_error(y_test, y_test_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

metrics_train = {"mean_squared_error_train" : mse_train,
                "mean_absolute_error_train": mae_train}

metrics_test = {"mean_squared_error_test": mse_test,
               "mean_absolute_error_test": mae_test}

print("Train_Data: ", metrics_train)
print("Test_Data:", metrics_test)


y_pred = Linear_model.predict(df2[["A","B"]])

mse_y_pred = mean_squared_error(df2["Target"], y_pred)
mae_y_pred = mean_absolute_error(df2["Target"], y_pred)

metrics_y_pred_linear = {"mean_squared_error_test": mse_y_pred,
                        "mean_absolute_error_test": mae_y_pred}

print("y_pred_metrics:", metrics_y_pred_linear)

Train_Data:  {'mean_squared_error_train': 5.054234220218337, 'mean_absolute_error_train': 1.793708330761995}
Test_Data: {'mean_squared_error_test': 5.081486197345235, 'mean_absolute_error_test': 1.7839327239219742}
y_pred_metrics: {'mean_squared_error_test': 5.046436003951251, 'mean_absolute_error_test': 1.7990800530982607}